"""empty message

Revision ID: 6081fefff4ef
Revises: 421ba9f0ea0a
Create Date: 2020-02-11 21:21:45.986924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6081fefff4ef"
down_revision = "421ba9f0ea0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images", sa.Column("mime_type", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "mime_type")
    # ### end Alembic commands ###
