"""empty message

Revision ID: c82deeaee404
Revises: 305bf169ef28
Create Date: 2020-02-12 20:37:27.112422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c82deeaee404"
down_revision = "305bf169ef28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images", sa.Column("original_name", sa.String(length=511), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "original_name")
    # ### end Alembic commands ###
