#!/usr/bin/env bash

# Get directory of script
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"

cd "$DIR/../" || exit 1

PRE_COMMIT_FILE="$PWD/.git/hooks/pre-commit"

echo "Setting up pre-commit hook..."

[[ -f "$PRE_COMMIT_FILE" ]] && rm -f "$PRE_COMMIT_FILE"

ln -rs "$PWD/.scripts/pre-commit" "$PRE_COMMIT_FILE"
